CREATE UNLOGGED TABLE people (
    name text PRIMARY KEY NOT NULL,
    domain text NOT NULL,
    countryCode text NOT NULL,
    longitude float NOT NULL,
    latitude float NOT NULL,
    pageViewsEnglish bigint NOT NULL,
    birthYear smallint NOT NULL,
    birthState text NOT NULL,
    occupation text NOT NULL,
    en_curid smallint NOT NULL,
    numLangs smallint NOT NULL,
    birthCity text NOT NULL,
    averageViews float NOT NULL,
    totalPageViews int NOT NULL,
    countryName text NOT NULL,
    stdDevPageViews float NOT NULL,
    countryCode3 text NOT NULL,
    pageViewsNonEnglish int NOT NULL,
    dataset text NOT NULL,
    l_star float NOT NULL,
    gender text NOT NULL,
    industry text NOT NULL,
    hpi float NOT NULL,
    continentName text NOT NULL
);